name: Django CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9, 3.10.12, 3.11]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        
        touch .env
        echo API_ENDPOINT="https://xxx.execute-api.us-west-2.amazonaws.com" >> .env
        echo DB_NAME="django_db" >> .env
        echo DB_USER="postgres" >> .env
        echo DB_PASS="postgres" >> .env
        echo DB_HOST="localhost" >> .env
        echo DB_PORT="5432" >> .env
        echo SECRET_KEY="^%yvj*u_0(ila@6w9dg38nu%px!0sb2fd%9=4!%vu)x(wa6l_&" >> .env
        cat .env
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py test
